### ISSUE TITLE
It doesn't work properly

### ISSUE THREAD

**Issue by webtimisten** [Deep-Winter/rrule-parser.net#8]
Try using this string: FREQ=YEARLY;COUNT=30;INTERVAL=1;BYMONTH=8;BYMONTHDAY=1

It should look like this:
01-08-2022 00:00:00
01-08-2023 00:00:00
01-08-2024 00:00:00
...
...

But it response this:
01-01-2022 00:00:00
01-01-2023 00:00:00
01-01-2024 00:00:00
...
...

**Comment by Deep-Winter** [comment]
This lib does not calculate the occurrences, it converts a rrule into a readable string. Maybe you mean another lib?
